'''
    PI: Sean P. Peisert
    Author: Reinhard Gentz, Charles McParland

    NOTICE: This computer software was prepared by The Regents of the
    University of California and Sean Peisert, hereinafter the Contractor,
    under Contract No. DE-AC02-05CH11231 with the Department of Energy
    (DOE). All rights in the computer software are reserved by DOE on
    behalf of the United States Government and the Contractor as provided
    in the Contract. You (NSA) are authorized to use this computer software for
    Governmental purposes but it is not to be released or distributed to
    the public. NEITHER THE GOVERNMENT NOR THE CONTRACTOR MAKES ANY
    WARRANTY, EXPRESS OR IMPLIED, OR ASSUMES ANY LIABILITY FOR THE USE OF
    THIS SOFTWARE. This notice including this sentence must appear on any
    copies of this computer software.
'''

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: upmuStructKeyValueListProtobuf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='upmuStructKeyValueListProtobuf.proto',
  package='serviceCommon',
  serialized_pb=_b('\n$upmuStructKeyValueListProtobuf.proto\x12\rserviceCommon\"v\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\x14\n\nintegerVal\x18\x02 \x01(\x05H\x00\x12\x15\n\x0buIntegerVal\x18\x03 \x01(\rH\x00\x12\x12\n\x08\x66loatVal\x18\x04 \x01(\x02H\x00\x12\x13\n\tstringVal\x18\x05 \x01(\tH\x00\x42\x07\n\x05value\"J\n\x0cKeyValueList\x12\x10\n\x08\x63\x61tegory\x18\x01 \x02(\t\x12(\n\x07\x65lement\x18\x02 \x03(\x0b\x32\x17.serviceCommon.KeyValue\"d\n\x16upmuStructKeyValueList\x12\x11\n\ttimeStamp\x18\x01 \x02(\r\x12\x0c\n\x04name\x18\x02 \x02(\t\x12)\n\x04list\x18\x03 \x03(\x0b\x32\x1b.serviceCommon.KeyValueList')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_KEYVALUE = _descriptor.Descriptor(
  name='KeyValue',
  full_name='serviceCommon.KeyValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='serviceCommon.KeyValue.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='integerVal', full_name='serviceCommon.KeyValue.integerVal', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uIntegerVal', full_name='serviceCommon.KeyValue.uIntegerVal', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='floatVal', full_name='serviceCommon.KeyValue.floatVal', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stringVal', full_name='serviceCommon.KeyValue.stringVal', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='serviceCommon.KeyValue.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=55,
  serialized_end=173,
)


_KEYVALUELIST = _descriptor.Descriptor(
  name='KeyValueList',
  full_name='serviceCommon.KeyValueList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='category', full_name='serviceCommon.KeyValueList.category', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='element', full_name='serviceCommon.KeyValueList.element', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=249,
)


_UPMUSTRUCTKEYVALUELIST = _descriptor.Descriptor(
  name='upmuStructKeyValueList',
  full_name='serviceCommon.upmuStructKeyValueList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='serviceCommon.upmuStructKeyValueList.timeStamp', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='serviceCommon.upmuStructKeyValueList.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='list', full_name='serviceCommon.upmuStructKeyValueList.list', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=351,
)

_KEYVALUE.oneofs_by_name['value'].fields.append(
  _KEYVALUE.fields_by_name['integerVal'])
_KEYVALUE.fields_by_name['integerVal'].containing_oneof = _KEYVALUE.oneofs_by_name['value']
_KEYVALUE.oneofs_by_name['value'].fields.append(
  _KEYVALUE.fields_by_name['uIntegerVal'])
_KEYVALUE.fields_by_name['uIntegerVal'].containing_oneof = _KEYVALUE.oneofs_by_name['value']
_KEYVALUE.oneofs_by_name['value'].fields.append(
  _KEYVALUE.fields_by_name['floatVal'])
_KEYVALUE.fields_by_name['floatVal'].containing_oneof = _KEYVALUE.oneofs_by_name['value']
_KEYVALUE.oneofs_by_name['value'].fields.append(
  _KEYVALUE.fields_by_name['stringVal'])
_KEYVALUE.fields_by_name['stringVal'].containing_oneof = _KEYVALUE.oneofs_by_name['value']
_KEYVALUELIST.fields_by_name['element'].message_type = _KEYVALUE
_UPMUSTRUCTKEYVALUELIST.fields_by_name['list'].message_type = _KEYVALUELIST
DESCRIPTOR.message_types_by_name['KeyValue'] = _KEYVALUE
DESCRIPTOR.message_types_by_name['KeyValueList'] = _KEYVALUELIST
DESCRIPTOR.message_types_by_name['upmuStructKeyValueList'] = _UPMUSTRUCTKEYVALUELIST

KeyValue = _reflection.GeneratedProtocolMessageType('KeyValue', (_message.Message,), dict(
  DESCRIPTOR = _KEYVALUE,
  __module__ = 'upmuStructKeyValueListProtobuf_pb2'
  # @@protoc_insertion_point(class_scope:serviceCommon.KeyValue)
  ))
_sym_db.RegisterMessage(KeyValue)

KeyValueList = _reflection.GeneratedProtocolMessageType('KeyValueList', (_message.Message,), dict(
  DESCRIPTOR = _KEYVALUELIST,
  __module__ = 'upmuStructKeyValueListProtobuf_pb2'
  # @@protoc_insertion_point(class_scope:serviceCommon.KeyValueList)
  ))
_sym_db.RegisterMessage(KeyValueList)

upmuStructKeyValueList = _reflection.GeneratedProtocolMessageType('upmuStructKeyValueList', (_message.Message,), dict(
  DESCRIPTOR = _UPMUSTRUCTKEYVALUELIST,
  __module__ = 'upmuStructKeyValueListProtobuf_pb2'
  # @@protoc_insertion_point(class_scope:serviceCommon.upmuStructKeyValueList)
  ))
_sym_db.RegisterMessage(upmuStructKeyValueList)


# @@protoc_insertion_point(module_scope)
